[package]
name = "ctrlgen-derive"
version= "0.3.2"
license.workspace = true
description.workspace = true
author.workspace = true
repository.workspace = true
edition = "2021"

[lib]
proc-macro = true

[dependencies]
ctrlgen-impl.workspace = true
proc-macro2 = "1.0.36"
